### ISSUE TITLE
Failed to Create CT

### ISSUE THREAD

**Issue by MekayelAnik** [thushan/proxmox-vm-to-ct#2]
unable to create CT 101 - command 'lxc-usernsexec -m u:0:100000:65536 -m g:0:100000:65536 -- tar xpf - -z --totals --one-file-system -p --sparse --numeric-owner --acls --xattrs '--xattrs-include=user.*' '--xattrs-include=security.capability' '--warning=no-file-ignored' '--warning=no-xattr-write' -C /var/lib/lxc/101/rootfs --skip-old-files --anchored --exclude './dev/*'' failed: exit code 2

**Comment by MekayelAnik** [comment]
> unable to create CT 101 - command 'lxc-usernsexec -m u:0:100000:65536 -m g:0:100000:65536 -- tar xpf - -z --totals --one-file-system -p --sparse --numeric-owner --acls --xattrs '--xattrs-include=user._' '--xattrs-include=security.capability' '--warning=no-file-ignored' '--warning=no-xattr-write' -C /var/lib/lxc/101/rootfs --skip-old-files --anchored --exclude './dev/_'' failed: exit code 2

Full Console Output:
  Logical volume "vm-101-disk-0" created.
Creating filesystem with 5242880 4k blocks and 1310720 inodes
Filesystem UUID: 124d5ea7-4f5b-4e16-976b-b3c5c3055e07
Superblock backups stored on blocks: 
        32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632, 2654208, 
extracting archive '/root/proxmox-dietpi-lxc.tar.gz'
tar: ./mnt/dietpi_userdata/docker-data/volumes/backingFsBlockDev: Cannot mknod: Operation not permitted
Total bytes read: 1030942720 (984MiB, 210MiB/s)
tar: Exiting with failure status due to previous errors
  Logical volume "vm-101-disk-0" successfully removed.
unable to create CT 101 - command 'lxc-usernsexec -m u:0:100000:65536 -m g:0:100000:65536 -- tar xpf - -z --totals --one-file-system -p --sparse --numeric-owner --acls --xattrs '--xattrs-include=user.*' '--xattrs-include=security.capability' '--warning=no-file-ignored' '--warning=no-xattr-write' -C /var/lib/lxc/101/rootfs --skip-old-files --anchored --exclude './dev/*'' failed: exit code 2

**Comment by thushan** [comment]
Hi @MekayelAnik,

did you use the `proxmox-vm-to-ct` script to generate this? If so what were the arguments sent to the script? (mask any passwords/sensitive things).

**Comment by MekayelAnik** [comment]
> Hi @MekayelAnik,
> 
> did you use the `proxmox-vm-to-ct` script to generate this? If so what were the arguments sent to the script? (mask any passwords/sensitive things).

Yes, I have used `proxmox-vm-to-ct` to generate this.
No, there was no arguments sent to this script as everything was at it's default `root : dietpi`.
Your script is very good. I was able to convert vm to ct when there was no installations were made i.e. Just created the VM not even started it for once, then the script works as a charm.
But at the 1st time I wanted to convert a VM with all the intended software installed through `dietpi-software`, in my case `docker`.
Then the script will finish `rsync` but will throw error when it will try to launch the converted image to container.

That's why I had to convert the raw untouched VM to CT, after that I installed all my things and made it a template. 

Also one other thing, I tried to stop the CLEANUP after the failed Container deployment. Edited the script to do so, but it didn't.
Thanks a lot. You did an outstanding job. The most straight forward Conversion Procedure I have encountered. It just needs a little touch ups.
Regards

**Comment by thushan** [comment]
Hey mate,

Thank-you for your very kind words, and thanks to bug reports like this, you're finding cases that will make it even better! So thank-you for opening the issue :)

Oh I see, I haven't installed docker into my 'base' VM prior to CT - that's done after, only the bare essentials (like tmux, some config changes). Docker may be a complication and haven't looked into that yet - but will now. One does need to enable `nesting` and `keyctl` features and I'm sorry I haven't had a chance to add the flags for non-default options yet due to work life.

Will try and reproduce this tonight. 

So that I understand, you have the latest DietPi in a VM  and via `dietpi-software` installed:

- Docker
(nothing else?)

Then used the script to convert the said VM to a CT.

Also to avoid cleaning up, you can use the `--source-output`, `--output` or `-o` switch and save it somewhere, for example:

```bash
./proxmox-vm-to-ct.sh --source 192.168.0.152 \
                      --target the-matrix-reloaded \
                      --storage local-lvm \
                      --default-config \
                      --prompt-password \
                      --output ~/dietpi-dockerised.tar.gz
```
The idea was that with a saved output, a future feature would continue to use that *.tar.gz to create containers instead of having to repeat this every time (on the TODO list!). Apologies.

**Comment by MekayelAnik** [comment]
> Hey mate,
> 
> Thank-you for your very kind words, and thanks to bug reports like this, you're finding cases that will make it even better! So thank-you for opening the issue :)
> 
> Oh I see, I haven't installed docker into my 'base' VM prior to CT - that's done after, only the bare essentials (like tmux, some config changes). Docker may be a complication and haven't looked into that yet - but will now. One does need to enable `nesting` and `keyctl` features and I'm sorry I haven't had a chance to add the flags for non-default options yet due to work life.
> 
> Will try and reproduce this tonight.
> 
> So that I understand, you have the latest DietPi in a VM and via `dietpi-software` installed:
> 
> * Docker
>   (nothing else?)

I had installed `tmux` as you mentioned that `tmux` or something like that is a must. Done some changes in `dietpi-config` such as `Time-Zone`, `DNS` in the NETWORK section. Things like that.
Note: I was able to make the container without installing `tmux` . I didn't touch the VM. Just imported the `dietpi.qcow2`. That's it. Didn't even gave first run.


> Also to avoid cleaning up, you can use the `--source-output`, `--output` or `-o` switch and save it somewhere, for example:
> 
> ```shell
> ./proxmox-vm-to-ct.sh --source 192.168.0.152 \
>                       --target the-matrix-reloaded \
>                       --storage local-lvm \
>                       --default-config \
>                       --prompt-password \
>                       --output ~/dietpi-dockerised.tar.gz
> ```
> 

I think yes. Not certain. I was in stress that time. Please have a look in the Cleanup section. Maybe I have done something wrong then. When it wasn't working, I edited the script: `OPT_CLEANUP` in the place of `OPT_SOURCE_OUTPUT`. My lousy head at that moment. Unbelievable!

> The idea was that with a saved output, a future feature would continue to use that *.tar.gz to create containers instead of having to repeat this every time (on the TODO list!). Apologies.

This was my first time converting VM into LXC. Thanks to you, it was way Easier than I thought it would be.

**Comment by thushan** [comment]
> I had installed `tmux` as you mentioned that `tmux` or something like that is a must. Done some changes in `dietpi-config` such as `Time-Zone`, `DNS` in the NETWORK section. Things like that.

Ah no, not required, `tmux` is like `screen` in the old days, makes working in terminal so much easier, have a look at [tmux features](https://www.youtube.com/watch?v=Yl7NFenTgIo) and you can also see [my tmux config](https://github.com/thushan/dotfiles/blob/main/.tmux.conf) to get started :-)

> I think yes. Not certain. I was in stress that time. Please have a look in the Cleanup section. Maybe I have done something wrong then. When it wasn't working, I edited the script: `OPT_CLEANUP` in the place of `OPT_SOURCE_OUTPUT`. My lousy head at that moment. Unbelievable!

No  problemo. It could be handled better, I just like to keep things clean and operate on, if i take a dump (of a temporary file) somewhere, i clean up.

The good news is I've gone all out and created a DietPi 8 with what you installed (and maybe more, because why not!):

![installing-docker-proxmox-ct](https://github.com/thushan/proxmox-vm-to-ct/assets/68254/e4c9c68f-00f8-4f07-9f9f-c845dda8631d)

Then I reproduced your issue:

![proxmox-docker-container-issue](https://github.com/thushan/proxmox-vm-to-ct/assets/68254/8415d07e-570a-4728-b775-6b44f4350cbd)

(that green bar at the bottom is `tmux` btw, really basic, allows you to tab between bash sessions I have...)

I suspect because the VM->CT for docker one needs:

- `nesting`
- `keyctl`
- privileged container

I will have to do some work and look at how to solve it nicely.

**Comment by thushan** [comment]
I think I've got it @MekayelAnik, unfortunately to enable this, you need to run a privileged container with a few more features as mentioned above.

Opened #3 which has all the details, are you able to grab that branch and try that and see if it works for you with the new switch?

This is what I get with the new `--default-config-containerd` switch I added in that branch:

![image](https://github.com/thushan/proxmox-vm-to-ct/assets/68254/b85e45de-1800-4df3-ae9e-7041aaed9ce8)

Thanks.

**Comment by MekayelAnik** [comment]
@thushan Thanks a lot Brother.
Inshallah, I will do and let you know.

**Comment by MekayelAnik** [comment]
Sorry brother, the issue remains. I have recorded the issue.
Video Link: [proxmox-vm-to-ct (The Video will be removed after 5 days)](https://drive.google.com/file/d/1Vcm1qrqYn77qdVCVcNJDMqoEH0Ebg13F/view?usp=drive_link)

CMD that was run: 
1.
```
./proxmox-vm-to-ct.sh      \     
                   --source 10.7.99.99       \
                   --target test-ct          \
                   --storage local-lvm       \
                   --default-config          \
                   --ignore-prep             \
                   --default-config-containered
```
2.
```
./proxmox-vm-to-ct.sh      \     
                   --source 10.7.99.99       \
                   --target test-ct          \
                   --storage local-lvm       \
                   --default-config          \
                   --ignore-prep             \
                   --default-config-docker
```
3.
```
./proxmox-vm-to-ct.sh      \     
                   --source 10.7.99.99       \
                   --target test-ct          \
                   --storage local-lvm       \
                   --ignore-prep             \
                   --default-config-containered
```
Every time the same error.
```
Error Log:
  Logical volume "vm-100-disk-0" created.
Creating filesystem with 5242880 4k blocks and 1310720 inodes
Filesystem UUID: e69664e8-6efe-4fb9-b028-f8a61f9e8aad
Superblock backups stored on blocks:
        32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632, 2654208,
extracting archive '/tmp/proxmox-vm-to-ct/10.7.99.99.tar.gz'
tar: ./mnt/dietpi_userdata/docker-data/volumes/backingFsBlockDev: Cannot mknod: Operation not permitted
Total bytes read: 657152000 (627MiB, 202MiB/s)
tar: Exiting with failure status due to previous errors
  Logical volume "vm-100-disk-0" successfully removed.
unable to create CT 100 - command 'lxc-usernsexec -m u:0:100000:65536 -m g:0:100000:65536 -- tar xpf - -z --totals --one-file-system -p --sparse --numeric-owner --acls --xattrs '--xattrs-include=user.*' '--xattrs-include=security.capability' '--warning=no-file-ignored' '--warning=no-xattr-write' -C /var/lib/lxc/100/rootfs --skip-old-files --anchored --exclude './dev/*'' failed: exit code 2
```

**Comment by thushan** [comment]
Hey mate,

Thanks for the video & trying it. Apologies, I should have mentioned it only needs `--default-config-containerd`, not both. If you remove the `--default-config` I have feeling it should be good.

When the script runs, before the password prints, it should show default config: 2, right now it's 1. I'll fix that up too.

Thanks again for trying it.

**Comment by MekayelAnik** [comment]
Alhamdulillah. I am glad to help a little. But I am really sorry, still facing the same problem. Don't know why. :(
I am [UPLOADING](https://drive.google.com/file/d/1a7wo0Ra9O1KTpeUrveB-K3Ba6SGzDjL6/view?usp=sharing) another video as well as the [SHELL FILE](https://drive.google.com/file/d/14zlnQtB7AL1V8yn7KN9XCx8IDUKPGMou/view?usp=sharing) I am using for the conversion. Please have a look,if I have done something wrong.

**Comment by thushan** [comment]
Oh my goodness, I just realised what has happened. I misspelt the argument, you're using `--default-config-containered` instead of `--default-config-containerd`. it's containerd not  containered.

I think my mac autocorrects containerd to containered.

Try it like this:

```
./proxmox-vm-to-ct.sh --source 10.7.99.99 \
                      --target test-ct    \
                      --storage local-lvm \
                      --ignore-prep       \
                      --default-config-containerd
```
Or even easier:

```shell
./proxmox-vm-to-ct.sh --source 10.7.99.99 \
                      --target test-ct    \
                      --storage local-lvm \
                      --ignore-prep       \
                      --default-config-docker
```

![image](https://github.com/thushan/proxmox-vm-to-ct/assets/68254/d891d3f2-0221-4417-80f5-a640f8612d5a)

I will check if I made those mistakes in the script. Though I think the autocorrect is only in my Firefox. So sorry, completely missed this.

**Comment by rusticslayer** [comment]
hi

Thanks for this script! It has been very valuable to us because we had lots of issues manually doing. We can confirm this works for me with dietpi9 vm to container compared to main branch.

We could use

```
./proxmox-vm-to-ct.sh --source voxel-engine-master-image \
                      --target voxel-engine-ct-node-1    \
                      --storage local-zfs \
                      --default-config-containerd
```

dietpi preparation was also very welcome, we had no idea. we also used again with debian12 images with `--ignore-prep` and works wunderbar gut!

thank you again.

**Comment by thushan** [comment]
thanks for the comments @rusticslayer good to see someones tried this with dietpi9 that was released only a few days ago!! will merge that PR but will leave this open for @MekayelAnik to comment when they're ready.
